travis:
  secure:
    BINSTAR_TOKEN: rxL2SqcE++zlcGS5CYPxuZuxD5IiG3LiCH5KQZwW+9o03wPugMlJ5vXmFiyXrTL3nTmxS7ZeY8xtHk4E52QA0GfiuOmOOtxKfj3OimAL/kuW2dcAb3UiDlGRjKcYxJogHWg9InRnpllk060JU7CBzZFclxr/yCUQx4iWTjYaoIpDw+jLQAcs0FnZFnQCC6uw30Hjqd/XrjrmLP0icwTUR0SCFnE28cq5Qp04qb0ZwxHC0uiBu6vEcoafFr2FKvyBgFqMYnG9ut/URuFEh26lzdgIW+2RzENiMRoDT12/BRHxzA3wlxY93xGc6QxhGzPc4IuSa6LK66HLjLqWJmmYpXJZHHxMI4SnRoMOyA53MhXiCbtLE5PzqNbG0DdDYUO9AFal6gfdQHEf89ktDoHUHUWXXB/RvF7rlV1OE0eIHbBl8+gjUY+WWojb34C6WxDfQBMuGl3vZx76g3m9KT+tNLHC7DFOnfPlKAuhuI9oXF9wXcElV560HhKc7D93nm7yYRYmnPtADWR8bn4ndQa5vCZzLEP3oqjb2WqUS+Jo9VGRIzDdsiufHpRuNKl40T7MctKqoKVZnQNreUnyAm1oQE0D2IpIfs/HZRfzwuuwai6jqTU1b4N7kqqFuFL7wrGYUMci6tyaKceQsLs+uzh53/KA3fhfgLTCpRCxlFTTsV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
